// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywlytwnkrenkimogemws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3bHl0d25rcmVua2ltb2dlbXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDY5NjksImV4cCI6MjA3NDEyMjk2OX0.FzUPXw_tF5-p9qQ5w-tOROYYdBqyNyUIOudgSoA9W8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});